title: Resume
resume:
  name: Li Zhiwei
  jobtitle: Undergraduate student major in Computer Science
  contact:
    - icon: fa-envelope
      text: jevis.li@outlook.com
    - icon: fa-phone-square
      text: 158-380-*****
    - icon: fa-globe
      text: your-website.com
      link: https://crispgm.github.io/resume/resume.html
    - icon: fa-github
      text: mtics
      link: https://github.com/mtics
  education:
    - university: Zhengzhou University
      link: https://en.wikipedia.org/wiki/Zhengzhou_University# Your university's link
      duration: Sep 2016 - July 2020
      location: Zhengzhou, Henan, China
      major: Computer Science
  skills:
    - title: Java Web
      items: Java, Spring, SpringBoot, Html/CSS
    - title: Others
      items: Python, C/C++, MySQL 
  experience:
    - title: Job Title 1
      duration: Apr 2016 - Now
      company: Your 1st, Inc.
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    - title: Job Title 2
      duration: Apr 2013 - Mar 2016
      company: Your 2nd, Inc.
      description: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    - title: Job Title 3
      duration: Dec 2011 - Mar 2012
      company: Your 3rd Co, Ltd.
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  projects:
    - name: XiaoJiaBiYu System
      description: Completed a Simple Heating Temperature Control System. The system is able to limit the flow of water in thepipeline by operation the solenoid valve installed on the heating pipeline, so that the indoor environment could achieve a suitable temperature. Be in charge of the APP development for remote control through android phones.
      contribution: Developer.
    - name: Pocket Electronics Lab based on mixed reality technology
      description: The project is a National-level College Student Entrepreneur Project. By developing an APP to scan the circuit diagram in the physics textbook to see the three-dimensional display, thereby simulating the experimental process and helping students to conduct experimental analysis by designing their own circuits. Be in charge of the modeling of circuit diagrams and electrical components by using Unity3D.
      contribution: Developer.
  languages:
    - name: English
      proficiency: Work proficiency
    - name: Mandarin Chinese
      proficiency: Native
